# from flask import Blueprint, jsonify, request, abort
# from main import db
# from Models.tenant import Tenant
# from Schemas.tenant_schema import tenant_schema, tenants_schema
# from datetime import date

# tenants = Blueprint('db', __name__, url_prefix="/tenants")

# # The GET routes endpoint
# @tenants.route("/", methods=["GET"])
# def get_tenants():
#     # get all the cards from the database table
#     stmt = db.select(Tenant)
#     tenants_list = db.session.scalars(stmt)
#     # Convert the cards from the database into a JSON format and store them in result
#     result = tenants_schema.dump(tenants_list)
#     # return the data in JSON format
#     return jsonify(result)

# # The POST route endpoint
# @tenants.route("/", methods=["POST"])
# def create_tenants():
#     # #Create a new card
#     tenant_fields = tenant_schema.load(request.json)

#     new_tenant = Tenant()
#     new_tenant.date_of_birth = tenant_fields["date_of_birth"]
#     new_tenant.name = tenant_fields["name"]
#     new_tenant.phone = tenant_fields["phone"]
#     new_tenant.email = tenant_fields["email"]
#     # not taken from the request, generated by the server
#     new_tenant.date = date.today()
#     # add to the database and commit
#     db.session.add(new_tenant)
#     db.session.commit()
#     #return the card in the response
#     return jsonify(tenant_schema.dump(new_tenant))


# # Finally, we round out our CRUD resource with a DELETE method
# @tenants.route("/<int:id>/", methods=["DELETE"])
# def delete_tenant(id):
#     # #get the user id invoking get_jwt_identity
#     # user_id = get_jwt_identity()
#     # #Find it in the db
#     # stmt = db.select(User).filter_by(id=user_id)
#     # user = db.session.scalar(stmt)
#     # #Make sure it is in the database
#     # if not user:
#     #     return abort(401, description="Invalid user")
#     # # Stop the request if the user is not an admin
#     # if not user.admin:
#     #     return abort(401, description="Unauthorised user")
#     # find the card
#     stmt = db.select(tenant).filter_by(id=id)
#     tenant = db.session.scalar(stmt)
#     #return an error if the card doesn't exist
#     if not tenant:
#         return abort(400, description= "tenant doesn't exist")
#     #Delete the card from the database and commit
#     db.session.delete(tenant)
#     db.session.commit()
#     #return the card in the response
#     return jsonify(tenant_schema.dump(tenant))